"""The Review Queue: every post ordered by Triage Priority, at a stated review depth.

The queue is a projection of the Policy Score and nothing else. It orders every Content
Item — in this build, every post the scores file holds — and it reads the two files this
project publishes about a Corpus: the scores and the Campaign Candidates. It runs no rule of
its own: no Corpus, no Public Suffix List, no weight set, and no membership, so it cannot
reach inference even by accident and it cannot measure anything by accident either
(ADR-0018). A queue whose order could disagree with the numbers printed beside it would
be worse than no queue, because a reviewer would act on the order and audit the score.

Triage Priority is therefore the Policy Score. Two posts can display the same one, because
the score is points rounded, so a tie is broken on the points earned and then on the post
id. The points are the same arithmetic one step finer than the figure on display; the post
id is stability rather than judgement, and it is the last key because a queue with nothing
else in its ordering would print a different one every time the Corpus changed. Nothing
else is consulted: not an account's age or posting rate, not a model output, not the size
of a Campaign Candidate, each of which could put a lower-scoring post above a higher one.

Every entry carries the Signal-by-Signal breakdown that produced its score and names the
Campaign Candidates the post sits in. A queue is the one output where that has to survive
being projected: the reviewer is being told which posts to read first, and a severity with
no arithmetic beside it at that moment is a severity they have to take on trust.

Nothing here is measured. Whether the ordering is any good is a question about how many of
the entries at a stated depth turned out to be findings, and answering it needs a
reviewer's judgement about each of them.
"""

from __future__ import annotations

import hashlib
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path

from reddit_fraud_intelligence.campaigns import (
    CampaignCandidate,
    read_campaign_candidates,
)
from reddit_fraud_intelligence.signals import PostScore, read_policy_scores
from reddit_fraud_intelligence.text import wrap

_HEADING = "Review Queue"

# Wrapped rather than continued, so the paragraph is as many lines a reader sees as the
# footer below it is. A backslash-continued literal is one very long line at run time,
# which is the shape this project's console output is trying not to have.
_SUBHEADING = """\
The order is Triage Priority, which is the Policy Score and nothing else (ADR-0003). Every
Signal behind a score is printed with it, and every Campaign Candidate a post sits in is
named beside it, so an entry can be worked from this output without running another
command."""


@dataclass(frozen=True, slots=True)
class QueueEntry:
    """One post in the queue: the score it was given, and the candidates holding it.

    The whole of `PostScore` rather than its number, because the number without the
    Signals behind it is the one thing this output must not print on its own.
    """

    score: PostScore
    candidates: tuple[CampaignCandidate, ...]


@dataclass(frozen=True, slots=True)
class QueueFacts:
    """What reading the two published files establishes, as claims about bytes.

    Both digests are printed because both files can be regenerated by a different command
    over a different Corpus, and a queue that says which bytes it ordered is a queue a
    reader can reproduce rather than take on trust.
    """

    candidates: int
    candidates_path: str
    candidates_sha256: str
    candidate_posts: int
    posts: int
    posts_with_signals: int
    scores_path: str
    scores_sha256: str


@dataclass(frozen=True, slots=True)
class ReviewQueue:
    """One run's queue, the depth it was asked for, and what it was read from.

    `depth` is carried rather than inferred from the entries, so a run that printed the
    whole file and a run that asked for the whole file cannot be confused for one another
    by the length of the table alone.
    """

    facts: QueueFacts
    depth: int
    entries: tuple[QueueEntry, ...]

    @property
    def below(self) -> int:
        """How many posts this run did not order: the whole file less the queue."""
        return self.facts.posts - len(self.entries)


def build_queue(scores_path: Path, candidates_path: Path, depth: int) -> ReviewQueue:
    """Read the two published files and order every post in the scores file by priority.

    One call, for the same reason the grouping and the scoring are one call: the figures,
    the order, and the evidence the order is read out of are three views of one pass over
    two files, and a caller that read them twice could end up printing one run's figures
    over another's entries.

    The scores are not re-derived and the grouping is not re-run. Both are functions of the
    Corpus, and both are held to the bytes their own command writes, so a queue that
    recomputed them could describe a Corpus nobody has a file for. Reading the published
    files is also what keeps this path unable to reach inference, which is the property
    the boundary of ADR-0018 exists for.

    The depth is refused rather than clamped below one. An empty queue printed under a
    header that says so is indistinguishable at a glance from a Corpus in which nothing is
    worth reading, and that is a claim about the Corpus this command has no business
    making.
    """
    if depth < 1:
        raise ValueError(
            f"a review depth of {depth} orders nothing, and an empty queue reads like a "
            "Corpus with nothing in it worth reviewing"
        )

    scores = read_policy_scores(scores_path)
    candidates = read_campaign_candidates(candidates_path)
    _refuse_unknown_posts(scores_path, candidates_path, scores, candidates)

    linked = _linked(candidates)
    ordered = sorted(
        scores, key=lambda score: (-score.score, -score.points, score.post_id)
    )[:depth]
    return ReviewQueue(
        facts=_facts(scores_path, candidates_path, scores, candidates),
        depth=depth,
        entries=tuple(
            QueueEntry(score=score, candidates=linked.get(score.post_id, ()))
            for score in ordered
        ),
    )


def _refuse_unknown_posts(
    scores_path: Path,
    candidates_path: Path,
    scores: Sequence[PostScore],
    candidates: Sequence[CampaignCandidate],
) -> None:
    """Refuse two published files that do not describe the same Corpus.

    One check, and it is the join's own. A candidate naming a post the scores file does
    not hold is a grouping over a Corpus this run has not scored, and a queue that quietly
    left that candidate out would be hiding the disagreement behind a shorter table: every
    entry it did print would be right, and the reader would have no way to know that the
    files named posts the run had not ranked.

    Refused rather than reported, which is the trade the evaluator makes over the same
    join, and the cost is worth naming: a candidates file left behind by an earlier run
    over a different Corpus stops this one rather than printing a ranked list over it. The
    remedy is to re-run `rfi campaign-candidates`, and a queue whose entries cannot be
    checked against the candidates file is not the deliverable this command exists for.
    """
    scored = {score.post_id for score in scores}
    unknown = sorted(
        {post for candidate in candidates for post in candidate.posts if post not in scored}
    )
    if unknown:
        raise ValueError(
            f"{candidates_path.as_posix()} names {unknown}, and "
            f"{scores_path.as_posix()} holds no such post: the two published files do not "
            "describe the same Corpus"
        )


def _linked(candidates: Sequence[CampaignCandidate]) -> Mapping[str, tuple[CampaignCandidate, ...]]:
    """Which candidates hold which posts, in the candidates file's own order.

    One pass over the candidates rather than a walk per post, because every entry asks the
    same question about its own post and the answer must not depend on how many posts the
    queue holds. The file's order rather than a sort, because the grouping wrote it in an
    order that means something — the biggest component first — and a queue that reordered
    it would print candidates in an order the reader has not been shown the reason for.
    """
    linked: dict[str, list[CampaignCandidate]] = {}
    for candidate in candidates:
        for post_id in candidate.posts:
            linked.setdefault(post_id, []).append(candidate)
    return {post_id: tuple(found) for post_id, found in linked.items()}


def _facts(
    scores_path: Path,
    candidates_path: Path,
    scores: Sequence[PostScore],
    candidates: Sequence[CampaignCandidate],
) -> QueueFacts:
    """Every figure about the two files the table prints, from the rows and the bytes."""
    return QueueFacts(
        candidates=len(candidates),
        candidates_path=candidates_path.as_posix(),
        candidates_sha256=hashlib.sha256(candidates_path.read_bytes()).hexdigest(),
        candidate_posts=len({post for candidate in candidates for post in candidate.posts}),
        posts=len(scores),
        posts_with_signals=sum(1 for score in scores if score.signals),
        scores_path=scores_path.as_posix(),
        scores_sha256=hashlib.sha256(scores_path.read_bytes()).hexdigest(),
    )


def render_table(queue: ReviewQueue) -> str:
    """The console output: what was read and at what depth, then the queue, then the
    arithmetic behind every entry of it.

    ASCII only, so it prints the same way on a console that cannot encode anything else
    and the same way when it is redirected, which is what lets it be pasted into an issue
    or diffed between runs. Sections are joined by one blank line, and the index and the
    blocks under it are in the same order because a reader who has just read a line of the
    index scrolls down looking for the entry it named.
    """
    sections = (
        f"{_HEADING}\n\n{_opening(queue)}",
        _figures(queue),
        _index(queue),
        "\n\n".join(_block(rank, entry) for rank, entry in enumerate(queue.entries, start=1)),
        _footer(),
    )
    return "\n\n".join(section for section in sections if section) + "\n"


def _opening(queue: ReviewQueue) -> str:
    """The depth this run was asked for, over the file it was asked to order.

    The depth is in the header rather than in a filename or a command line, because a queue
    pasted into an issue without it says nothing about what was left below it. Both figures
    are named in one sentence, and a depth the file cannot fill says so in the same line:
    "the top 50" over a 34-post file must not read as a claim that 50 posts were worth
    reading. The posts below the cut are ordered and not printed — the whole file is
    sorted, and the depth decides how much of it to show — which the closing section says
    too, because a header read the other way would say this run left them unranked.
    """
    facts = queue.facts
    cut = (
        f"Review depth {queue.depth} of the {facts.posts} posts {facts.scores_path} holds, "
        f"so {queue.below} of them sit below the cut and are not printed here."
        if queue.below
        else f"Review depth {queue.depth} of the {facts.posts} posts {facts.scores_path} "
        "holds, so nothing was cut."
    )
    return "\n".join([*wrap(cut, indent=0, width=100), _SUBHEADING])


def _figures(queue: ReviewQueue) -> str:
    """What was read, and what came of it. One figure per line, labelled."""
    facts = queue.facts
    figures = (
        ("depth", f"{queue.depth} of the {facts.posts} posts in the scores file"),
        (
            "scores",
            f"{facts.scores_path} ({_count(facts.posts, 'post')}, "
            f"{facts.posts_with_signals} carrying a Signal)",
        ),
        ("scores sha256", facts.scores_sha256),
        (
            "candidates",
            f"{facts.candidates_path} ({_count(facts.candidates, 'candidate')} over "
            f"{_count(facts.candidate_posts, 'post')})",
        ),
        ("candidates sha256", facts.candidates_sha256),
        (
            "queue",
            f"{len(queue.entries)} of the {facts.posts} posts ordered, "
            f"{sum(1 for entry in queue.entries if entry.score.signals)} carrying a Signal",
        ),
    )
    width = max(len(name) for name, _ in figures)
    return "\n".join(f"  {name.ljust(width)}  {value}" for name, value in figures)


def _count(number: int, noun: str) -> str:
    """One count, agreeing with its noun. Every figure here is small, and a reader seeing
    "1 posts" stops to wonder whether the figure is right."""
    return f"{number} {noun if number == 1 else f"{noun}s"}"


def _index(queue: ReviewQueue) -> str:
    """One line per entry, in the order the blocks below are printed.

    The Signals column counts rather than names them, because a row naming four of them is
    a row 150 columns wide and the names are two lines further down in the entry's own
    block. An empty queue says so here rather than leaving a heading over nothing.
    """
    if not queue.entries:
        return "No post to order: the scores file holds none."

    headings = ("rank", "post", "account", "score", "signals", "candidates")
    rows = [
        (
            str(rank),
            entry.score.post_id,
            entry.score.account,
            str(entry.score.score),
            str(len(entry.score.signals)),
            ", ".join(candidate.candidate_id for candidate in entry.candidates) or "-",
        )
        for rank, entry in enumerate(queue.entries, start=1)
    ]
    widths = [max(len(cell) for cell in column) for column in zip(headings, *rows, strict=True)]
    return "\n".join([_row(headings, widths), *(_row(row, widths) for row in rows)])


def _row(cells: Sequence[str], widths: Sequence[int]) -> str:
    """One line of the index. A cell of nothing but digits is a count, and counts are
    right-aligned so the digits line up down the column; the rest is text of no fixed width
    and reads better against the left edge."""
    return "  ".join(
        cell.rjust(width) if cell.isdigit() else cell.ljust(width)
        for cell, width in zip(cells, widths, strict=True)
    )


def _block(rank: int, entry: QueueEntry) -> str:
    """One entry: every Signal, the weight it was earned at, and what fired it.

    The last line of the arithmetic is the total against the published total, so the
    division that produced the score on the heading line is written out rather than left to
    the reader. The candidates come under it with the registration each is joined on,
    because an identifier on its own says nothing to somebody who has not opened the
    candidates file.
    """
    score = entry.score
    lines = [f"{rank}  {score.post_id}  {score.account}  {score.score}/100"]
    if score.signals:
        name = max(len(hit.signal.value) for hit in score.signals)
        figures = max(len(str(hit.weight)) for hit in score.signals)
        for hit in score.signals:
            lines.append(
                f"  {hit.signal.value.ljust(name)}  {str(hit.weight).rjust(figures)}  "
                f"{hit.line()}"
            )
        lines.append(
            f"  {'total'.ljust(name)}  {str(score.points).rjust(figures)}  of "
            f"{score.published_points} published points, {len(score.signals)} of "
            f"{score.published_signals} Signals"
        )
    else:
        lines.append(
            f"  {_NO_SIGNAL}  this post carries none, and its Policy Score is 0 of "
            f"{score.published_points} published points"
        )
    lines.extend(_candidates(entry))
    return "\n".join(lines)


_NO_SIGNAL = "no Signal"

# The label column of an entry's block, as wide as the longest label printed in it, so
# every value in the block starts in the same column whichever shape the entry took.
_LABEL = max(len("candidates"), len(_NO_SIGNAL))


def _candidates(entry: QueueEntry) -> list[str]:
    """One line per candidate holding this post, or the line that says there is none.

    The dash is the project's own mark for a cell with nothing in it. It is printed rather
    than the line omitted, because an entry with no candidate line is indistinguishable
    from a run that joined nothing at all.
    """
    if not entry.candidates:
        return [f"  {'candidates'.ljust(_LABEL)}  -  no Campaign Candidate holds it"]
    return [
        f"  {'candidates'.ljust(_LABEL)}  {candidate.candidate_id}  "
        f"{_count(len(candidate.accounts), 'account')}, joined on "
        f"{_joined_on(candidate)}"
        for candidate in entry.candidates
    ]


def _joined_on(candidate: CampaignCandidate) -> str:
    """The registrations a candidate is joined on, which are why it exists (ADR-0005)."""
    domains = ", ".join(shared.domain for shared in candidate.shared_domains)
    return domains or "no registration this file names"


def _footer() -> str:
    """What the order can and cannot claim, and what it is not.

    The limits are the ones a reader would otherwise have to guess at: what the ordering
    was made of and what was deliberately left out of it, why the tail of the queue is
    printed rather than dropped, what a Campaign Candidate named beside an entry does and
    does not say, and the fact that no figure is computed over any of it.
    """
    return """\
Triage Priority is the Policy Score and nothing else, and nothing is consulted to produce
the order above: no account's age, karma, posting rate, or activity change is read, no
model output is involved, and the size of a Campaign Candidate moves nothing (ADR-0007).
Two posts that tie on the Policy Score are ordered by the points they earned of the
published total and then by the post id. The points are that same arithmetic one step finer
than the figure on display; the post id is the last key because a queue with nothing else
in its ordering would print a different one every time the Corpus changed.

The Signals column counts the Signals an entry carries. Each one is named in that entry's
own block with the weight it was earned at and the evidence behind it, so a reader can redo
the score by hand from what is printed beside it. A post carrying no Signal is ordered
rather than dropped: the depth says how far down the queue to go, and dropping the tail
would be a rule no weight file publishes. Everything below the cut is ordered too, by the
same rule, and simply not printed: the depth is what a run chose rather than a claim about
what the rest of the Corpus holds. The scores themselves are printed in full by
`rfi policy-score`, which states what they can and cannot claim.

A Campaign Candidate is a hypothesis produced by cohesion analysis, never a confirmed claim
about anyone's behaviour (ADR-0005). An entry naming one says that the post sits inside a
proposed grouping of accounts sharing a registration, and nothing more. Whether those
accounts belong together, and whether the post is worth acting on at all, are judgments this
command does not make, and nobody has reviewed any of it.

No figure is computed over this queue and nothing in it names one. Whether the ordering is
any good is a question about how many of the entries at this depth turned out to be
findings, and answering it needs a reviewer's judgement about each entry. That is a later
step, on its own terms."""